version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:14.0.0
    volumes:
      - "./keycloak/standalone-ha.xml:/opt/jboss/keycloak/standalone/configuration/standalone-ha.xml"
    environment:
      PROXY_ADDRESS_FORWARDING: "true"
      VIRTUAL_HOST: keycloak
      DB_VENDOR: POSTGRES
      DB_ADDR: prof-postgresql
      DB_DATABASE: keycloak
      DB_SCHEMA: public
      DB_USER: postgres
      DB_PASSWORD: 0a2161bdfe690b902303e1ab4730fe28
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8082:8080"
    depends_on:
      - prof-postgresql
  prof-postgresql:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - prof-db:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d/
    environment:
      - 'POSTGRES_PASSWORD=0a2161bdfe690b902303e1ab4730fe28'
          
volumes:
  prof-db:
