version: '3'
services:
      
  order-service-1:
    image: order-service
    ports:
      - 8081:8081
    environment:
      APP_PORT: 8081
      DB_URL: 192.168.0.199:5432
      KEYCLOAK_URL: http://192.168.0.199:8082
      LOGSTASH_URL: 192.168.0.199:12202
      ORDER_SERVICE_URL: http://192.168.0.199/order-service
      CONSUL_URL: http://192.168.0.199:8500
      
  order-service-2:
    image: order-service
    ports:
      - 8086:8086
    environment:
      APP_PORT: 8086
      DB_URL: 192.168.0.199:5432
      KEYCLOAK_URL: http://192.168.0.199:8082
      LOGSTASH_URL: 192.168.0.199:12202
      ORDER_SERVICE_URL: http://192.168.0.199/order-service
      CONSUL_URL: http://192.168.0.199:8500
